# Generated by Django 4.1.7 on 2023-04-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant', '0002_alter_image_author_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.FileField(help_text='выберите файл', upload_to='images1/'),
        ),
    ]
